/**
 * OOPSBannerApp UC6: Refactor Banner Logic into Functions
 * * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 * * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
<<<<<<< HEAD
 * * @author Varun sai 
=======
 * * @author Varun sai
>>>>>>> 93d9c7f60da3c76a906b0b2bd7bed8d3c78554eb
 * @version 2
 */

// Extend the User Story 4 to display the message "OOPS" in a banner format
// using characters formed by spaces and asterisks (*) to create a visual
// effect for each letter in the message. Use print statements for each line
// instead of a loop.

public class UC6_OOPSBannerApp {

    // Main method to run the banner display
    // Print each line of the OOPS banner to create the visual effect for the
    // message "OOPS". Construct each line using string concatenation.
    // Each line corresponds to a row in the banner for the letters O, O, P, S.
    // Using individual print statements for each line.
   
    public static void main(String[] args) {

        System.out.println("OOPS Banner App");
        System.out.println("UC6: Refactor Banner Logic into Functions");
        System.out.println();

        String[] o = getOPattern();
        String[] p = getPPattern();
        String[] s = getSPattern();

        // Combine letters O O P S
        String[] banner = new String[7];

        for (int i = 0; i < 7; i++) {
            banner[i] = String.join("  ", o[i], o[i], p[i], s[i]);
        }

        // Enhanced for loop to print
        for (String line : banner) {
            System.out.println(line);
        }
    }

    // Static Method for O
    public static String[] getOPattern() {
        return new String[] {
            " ***** ",
            "*     *",
            "*     *",
            "*     *",
            "*     *",
            "*     *",
            " ***** "
        };
    }
	
	// Static Method for O
    public static String[] getOPattern() {
        return new String[] {
            " ***** ",
            "*     *",
            "*     *",
            "*     *",
            "*     *",
            "*     *",
            " ***** "
        };
    }

    // Static Method for P
    public static String[] getPPattern() {
        return new String[] {
            "****** ",
            "*     *",
            "*     *",
            "****** ",
            "*      ",
            "*      ",
            "*      "
        };
    }

    // Static Method for S
    public static String[] getSPattern() {
        return new String[] {
            "*******",
            "*      ",
            "*      ",
            "*******",
            "      *",
            "      *",
            "*******"
        };
    }
}
